export const vegetables = [
  {
    id: '1',
    name: 'Cucumbers',
    price: 3.2,
    image: require('../../assets/images/GImages/cucumbers.png'), // Replace with your actual image path
    quantity: 1,
    unit: 'kg',
    selectedQuantity: 0,
  },
  {
    id: '2',
    name: 'Fresh garlic',
    price: 5.1,
    image: require('../../assets/images/GImages/garlic.png'),
    quantity: 1.2,
    unit: 'kg',
    selectedQuantity: 1.2,
  },
  {
    id: '3',
    name: 'Beetles',
    price: 5.1,
    image: require('../../assets/images/GImages/beetles.png'),
    quantity: 1,
    unit: 'kg',
    selectedQuantity: 0,
  },
  {
    id: '4',
    name: 'Tomatoes',
    price: 5.1,
    image: require('../../assets/images/GImages/tomatoes.png'),
    quantity: 1,
    unit: 'kg',
    selectedQuantity: 0,
  },
  {
    id: '5',
    name: 'Lemon',
    price: 5.1,
    image: require('../../assets/images/GImages/lemon.png'),
    quantity: 1,
    unit: 'kg',
    selectedQuantity: 0,
  },
  {
    id: '6',
    name: 'Patatoes',
    price: 5.1,
    image: require('../../assets/images/GImages/paratoes.png'),
    quantity: 1,
    unit: 'kg',
    selectedQuantity: 0,
  },
];
